os: osx

git:
  depth: 1

before_install:
  - brew install hugo

jobs:
  include:
    - stage: "Build & Deploy Pages"
      script: rm -rf public && hugo -D && cp CNAME public
      deploy:
        provider: pages
        local_dir: public
        repo: leiysky/leiysky.github.io
        target_branch: master
        skip_cleanup: true
        github_token: $SECRET_TOKEN
        keep_history: true
        on:
          branch: master
